version: '2'
services:
  web:
    image: gncloud/gncloud-web
    restart: always
    volumes:
      - /etc/nginx:/etc/nginx
      - /var/log/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - manager
      - kvm
      - docker
      - hyperv
      - scheduler

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: gncloud
      MYSQL_DATABASE: gncloud
      MYSQL_USER: gncloud
      MYSQL_PASSWORD: gncloud

  manager:
    image: gncloud/gncloud-manager
    volumes:
      - /var/log/gncloud:/var/log/gncloud
      - /root/.ssh:/root/.ssh
    ports:
      - "8080:80"
    restart: always
    environment:
      WSGI_PROCESSES: 4
      WSGI_THREADS: 2
    depends_on:
      - db


  kvm:
    image: gncloud/gncloud-kvm
    volumes:
      - /var/log/gncloud:/var/log/gncloud
      - /root/.ssh:/root/.ssh
    ports:
      - "8081:80"
    restart: always
    environment:
      WSGI_PROCESSES: 4
      WSGI_THREADS: 2
    depends_on:
      - db


  hyperv:
    image: gncloud/gncloud-hyperv
    volumes:
      - /var/log/gncloud:/var/log/gncloud
      - /root/.ssh:/root/.ssh
    ports:
      - "8082:80"
    restart: always
    environment:
      WSGI_PROCESSES: 4
      WSGI_THREADS: 2
    depends_on:
      - db


  docker:
    image: gncloud/gncloud-docker
    volumes:
      - /var/log/gncloud:/var/log/gncloud
      - /root/.ssh:/root/.ssh
    ports:
      - "8083:80"
    restart: always
    environment:
      WSGI_PROCESSES: 4
      WSGI_THREADS: 2
    depends_on:
      - db


  scheduler:
    image: gncloud/gncloud-scheduler
    volumes:
      - /var/log/gncloud:/var/log/gncloud
      - /root/.ssh:/root/.ssh
    ports:
      - "8084:80"
    restart: always
    environment:
      WSGI_PROCESSES: 4
      WSGI_THREADS: 2
    depends_on:
      - db


networks:
  front:
    driver: brigde

       # ssh-keygen -f ~/.ssh/id_rsa
       # ssh-copy-id -i ~/.ssh/id_rsa.pub root@192.168.1.2
       # ssh-copy-id -i ~/.ssh/id_rsa.pub root@192.168.1.201
       # ssh-copy-id -i ~/.ssh/id_rsa.pub root@192.168.1.202
       # ssh-copy-id -i ~/.ssh/id_rsa.pub root@192.168.1.203
       # ssh-copy-id -i ~/.ssh/id_rsa.pub root@192.168.1.204
       # docker run -d --name web-front -p 80:80 -v /var/log/nginx:/var/log/nginx -v /etc/nginx:/etc/nginx web-front
       # docker run -d --name manager-controller -p 8080:80 -v /var/log/gncloud:/var/log/gncloud -v /root/.ssh:/root/.ssh manager-controller
       # docker run -d --name kvm-controller -p 8081:80 -v /var/log/gncloud:/var/log/gncloud -v /root/.ssh:/root/.ssh kvm-controller
       # docker run -d --name hyperv-controller -p 8082:80 -v /var/log/gncloud:/var/log/gncloud -v /root/.ssh:/root/.ssh hyperv-controller
       # docker run -d --name docker-controller -p 8083:80 -v /var/log/gncloud:/var/log/gncloud -v /root/.ssh:/root/.ssh docker-controller
       # docker run -d --name scheduler -p 8084:80 -v /var/log/gncloud:/var/log/gncloud -v /root/.ssh:/root/.ssh scheduler
